//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.21 at 10:56:22 AM IST 
//


package com.bigyan.rrule.config.xml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bigyan.rrule.config.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bigyan.rrule.config.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RruleEngine }
     * 
     */
    public RruleEngine createRruleEngine() {
        return new RruleEngine();
    }

    /**
     * Create an instance of {@link CompositeRuleType }
     * 
     */
    public CompositeRuleType createCompositeRuleType() {
        return new CompositeRuleType();
    }

    /**
     * Create an instance of {@link CompositeRuleType.Composite }
     * 
     */
    public CompositeRuleType.Composite createCompositeRuleTypeComposite() {
        return new CompositeRuleType.Composite();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link RruleEngine.Rules }
     * 
     */
    public RruleEngine.Rules createRruleEngineRules() {
        return new RruleEngine.Rules();
    }

    /**
     * Create an instance of {@link SimpleRuleType }
     * 
     */
    public SimpleRuleType createSimpleRuleType() {
        return new SimpleRuleType();
    }

    /**
     * Create an instance of {@link CompositeRuleType.Composite.Rule }
     * 
     */
    public CompositeRuleType.Composite.Rule createCompositeRuleTypeCompositeRule() {
        return new CompositeRuleType.Composite.Rule();
    }

    /**
     * Create an instance of {@link PropertiesType.Entry }
     * 
     */
    public PropertiesType.Entry createPropertiesTypeEntry() {
        return new PropertiesType.Entry();
    }

}
